const express = require('express');
const router = express.Router();
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');
const { pool } = require('../config/database');
const KeyManager = require('../models/KeyManager');
const { adminAuth, rateLimiter, validateRequest } = require('../middleware/security');

router.post('/login', rateLimiter(5), async (req, res) => {
    try {
        const { username, password } = req.body;
        if (!username || !password) return res.status(400).json({ error: 'Missing credentials' });
        const { rows } = await pool.query('SELECT * FROM admins WHERE username = $1', [username]);
        if (rows.length === 0 || !bcrypt.compareSync(password, rows[0].password_hash)) {
            return res.status(401).json({ error: 'Invalid credentials' });
        }
        const admin = rows[0];
        await pool.query('UPDATE admins SET last_login = NOW() WHERE id = $1', [admin.id]);
        const token = jwt.sign(
            { id: admin.id, username: admin.username, role: admin.role },
            process.env.JWT_SECRET || 'jwt-secret-change-me',
            { expiresIn: '24h' }
        );
        res.json({ token, admin: { username: admin.username, role: admin.role } });
    } catch (err) {
        console.error('[LOGIN]', err);
        res.status(500).json({ error: 'Internal error' });
    }
});

router.post('/verify-token', adminAuth, (req, res) => {
    res.json({ valid: true, admin: req.admin });
});

router.get('/stats', adminAuth, async (req, res) => {
    try {
        const stats = await KeyManager.getStats();
        res.json(stats);
    } catch (err) {
        console.error('[STATS]', err);
        res.status(500).json({ error: 'Internal error' });
    }
});

router.get('/keys', adminAuth, async (req, res) => {
    try {
        const { status, plan_type, search, limit, offset } = req.query;
        const keys = await KeyManager.getAllKeys({
            status, plan_type, search,
            limit: parseInt(limit) || 200,
            offset: parseInt(offset) || 0
        });
        const sanitized = keys.map(k => ({ ...k, key_hash: k.key_raw || k.key_hash.substring(0, 16) + '...', key_display: k.key_raw || k.key_hash.substring(0, 16) + '...' }));
        res.json({ keys: sanitized, total: sanitized.length });
    } catch (err) {
        console.error('[KEYS_LIST]', err);
        res.status(500).json({ error: 'Internal error' });
    }
});

router.post('/keys/generate', adminAuth, async (req, res) => {
    try {
        const { duration, plan_type, count, prefix } = req.body;
        if (!duration || !plan_type || !count) return res.status(400).json({ error: 'Missing required fields' });
        if (count > 100) return res.status(400).json({ error: 'Max 100 keys per batch' });
        const keys = await KeyManager.createKeysBulk({
            count, duration, planType: plan_type, prefix: prefix || '', createdBy: req.admin.username
        });
        await KeyManager.logAction({
            key: 'bulk:' + count, hwid: '', ip: req.ip,
            action: 'generate_keys', status: 'success',
            details: `${count} keys generated by ${req.admin.username}`
        });
        res.json({ keys, count: keys.length });
    } catch (err) {
        console.error('[GENERATE]', err);
        res.status(500).json({ error: 'Internal error' });
    }
});

router.post('/keys/reset-hwid', adminAuth, async (req, res) => {
    try {
        const { key } = req.body;
        if (!key) return res.status(400).json({ error: 'Key is required' });
        const result = await KeyManager.resetHwid(key);
        await KeyManager.logAction({ key, hwid: '', ip: req.ip, action: 'reset_hwid', status: result ? 'success' : 'failed' });
        res.json({ success: result, message: result ? 'HWID reset' : 'Key not found' });
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

router.post('/keys/extend', adminAuth, async (req, res) => {
    try {
        const { key, days } = req.body;
        if (!key || !days) return res.status(400).json({ error: 'Key and days are required' });
        const result = await KeyManager.extendKey(key, days);
        await KeyManager.logAction({ key, hwid: '', ip: req.ip, action: 'extend_key', status: result ? 'success' : 'failed', details: `+${days} days` });
        res.json({ success: result, message: result ? `Extended by ${days} days` : 'Key not found' });
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

router.post('/keys/ban', adminAuth, async (req, res) => {
    try {
        const { key } = req.body;
        if (!key) return res.status(400).json({ error: 'Key is required' });
        const result = await KeyManager.banKey(key);
        await KeyManager.logAction({ key, hwid: '', ip: req.ip, action: 'ban_key', status: result ? 'success' : 'failed' });
        res.json({ success: result, message: result ? 'Key banned' : 'Key not found' });
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

router.post('/keys/unban', adminAuth, async (req, res) => {
    try {
        const { key } = req.body;
        if (!key) return res.status(400).json({ error: 'Key is required' });
        const result = await KeyManager.unbanKey(key);
        res.json({ success: result, message: result ? 'Key unbanned' : 'Key not found' });
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

router.post('/keys/delete', adminAuth, async (req, res) => {
    try {
        const { key } = req.body;
        if (!key) return res.status(400).json({ error: 'Key is required' });
        const result = await KeyManager.deleteKey(key);
        await KeyManager.logAction({ key, hwid: '', ip: req.ip, action: 'delete_key', status: result ? 'success' : 'failed' });
        res.json({ success: result, message: result ? 'Key deleted' : 'Key not found' });
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

router.get('/keys/info/:key', adminAuth, async (req, res) => {
    try {
        const record = await KeyManager.getKeyInfo(req.params.key);
        if (!record) return res.status(404).json({ error: 'Key not found' });
        res.json(record);
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

router.post('/hwid/ban', adminAuth, async (req, res) => {
    try {
        const { hwid, reason } = req.body;
        if (!hwid) return res.status(400).json({ error: 'HWID is required' });
        const result = await KeyManager.banHwid(hwid, reason || 'Banned by admin', req.admin.username);
        res.json({ success: result, message: result ? 'HWID banned and keys revoked' : 'Already banned' });
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

router.get('/logs', adminAuth, async (req, res) => {
    try {
        const { limit, offset } = req.query;
        const logs = await KeyManager.getLogs(parseInt(limit) || 100, parseInt(offset) || 0);
        res.json({ logs, total: logs.length });
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

router.get('/logs/recent', adminAuth, async (req, res) => {
    try {
        const minutes = parseInt(req.query.minutes) || 60;
        const logs = await KeyManager.getRecentLogs(minutes);
        res.json(logs);
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

router.post('/admin/change-password', adminAuth, async (req, res) => {
    try {
        const { currentPassword, newPassword } = req.body;
        if (!currentPassword || !newPassword) return res.status(400).json({ error: 'Missing passwords' });
        const { rows } = await pool.query('SELECT * FROM admins WHERE id = $1', [req.admin.id]);
        if (rows.length === 0 || !bcrypt.compareSync(currentPassword, rows[0].password_hash)) {
            return res.status(401).json({ error: 'Current password is incorrect' });
        }
        if (newPassword.length < 6) return res.status(400).json({ error: 'Password must be at least 6 characters' });
        const hash = bcrypt.hashSync(newPassword, 12);
        await pool.query('UPDATE admins SET password_hash = $1 WHERE id = $2', [hash, req.admin.id]);
        res.json({ success: true, message: 'Password changed' });
    } catch (err) {
        res.status(500).json({ error: 'Internal error' });
    }
});

module.exports = router;
